# Generated by Django 5.2.8 on 2025-12-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reminder",
            old_name="reminder_date",
            new_name="due_date",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="message",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="student",
        ),
        migrations.AddField(
            model_name="reminder",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="title",
            field=models.CharField(default="Untitled", max_length=100),
            preserve_default=False,
        ),
    ]
