# Generated by Django 5.2.8 on 2025-12-10 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_remove_assignment_student_alter_assignment_title"),
        ("students", "0002_remove_student_enrollment_date_student_reg_number_and_more"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="submitted_at",
            new_name="submitted_on",
        ),
        migrations.AddField(
            model_name="submission",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assignments.assignment"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="grade",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
    ]
